export const ADD_INGREDIENTS = "ADD_INGREDIENTS"
export const REMOVE_INGREDIENTS = "REMOVE_INGREDIENTS"
export const PRIZE_INGREDIENTS = "PRIZE_INGREDIENTS"
export const SET_INGREDIENTS = 'SET_INGREDIENTS'
export const FETCH_INGREDIENTSFAILED = 'FETCH_INGREDIENTSFAILED'

export const PURCHASEBURGERSUCESS = 'PURCHASEBURGERSUCESS'
export const PURCHASEBURGERFAIL = 'PURCHASEBURGERFAIL'
export const PURCHASEBURGERSTART = 'PURCHASEBURGERSTART'
export const PURCHASEINIT = 'PURCHASEINIT'

export const FETCHORDERSSUCESS = 'FETCHORDERSSUCESS'
export const FETCHORDERSFAIL = 'FETCHORDERSFAIL'
export const FETCHORDERSSTART = 'FETCHORDERSSTART'

export const AUTHSUCESS = "AUTHSUCESS"
export const AUTHFAIL = "AUTHFAIL"
export const AUTHSTART = "AUTHSTART"

export const LOGOUTUSER= "LOGOUTUSER"
export const REDIRECTAUTH = "REDIRECTAUTH"